language: java
install: true
jdk:
    - oraclejdk11

script:
    - sudo apt-get install gradle
    - gradle -v
    - cd server
    - gradle wrapper
    - chmod +x ./gradlew
    - ./gradlew clean test --info
