language: java
install: true
jdk:
    - oraclejdk11

install:
    - bash -c 'curl -s "https://get.sdkman.io" | bash'
    - source "/home/travis/.sdkman/bin/sdkman-init.sh"
    - sdk install gradle 5.0

script:
    - cd server
    - gradle wrapper
    - chmod +x ./gradlew
    - ./gradlew clean test --info
