language: java
install: true

before_install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
    include:
        - env: JDK='Oracle JDK 10'
          install: . ./install-jdk.sh -F 10 -L BCL

script:
    - cd server
    - gradle wrapper
    - chmod +x ./gradlew
    - ./gradlew clean test --info
