language: java
install: true
jdk:
    - oraclejdk11

script:
    - sdk install gradle 5.0
    - gradle -v
    - cd server
    - gradle wrapper
    - chmod +x ./gradlew
    - ./gradlew clean test --info
